니꼬쌤의 환경은 맥/리눅스 환경이죠... 만약 windows에서 작업하시는 분들이라면 .env를 '자동으로' 읽어오지 않습니다. 그래서 python_dotenv를 쓰셔야 합니다.
괜히 희망가졌다가... 좌절하고 다시 하던대로 갑니다.

1. python_dotenv 설치
uv add python-dotenv

2. 모든 파일, 노트의 가장 첫번째에서 다음과 같이 설정하여 환경변수를 불러다 둡니다.
from dotenv import load_dotenv
load_dotenv()

3. 이 아래쪽으로 니꼬쌤의 코드 입력.
>> 실행하면 KEY가 나오실 겁니다.

#%%
저도 계속 None이 떠서 아래와 같이 해결했습니다.
1. uv add python-dotenv
2. main.py를 아래와 같이 작성

```
import os

def main():
load_dotenv()
print(os.getenv("OPENAI_API_KEY"))
```

그런데 주피터에서는 load_dotenv()없이도 환경변수가 로드되네요.
이 차이점에 대해서는 잘 모르겠습니다.